api:
  insecure: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

entryPoints:
  websecure:
    address: ":443"
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

certificatesResolvers:
  le:
    acme:
      email: fcdd07@mail.ua
      storage: /certs/acme.json
      httpChallenge:
        entryPoint: web
