name: Deploy to Amazon EC2
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploying productions
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: 54.93.207.108
        username: ec2-user
        password: grow87654321
        port: 22
        script: |
          sudo rm -rf -f /home/ec2-user/app/ua_help
          sudo rm -rf -f /home/ec2-user/certs
          cd /home/ec2-user/app
          git clone https://github.com/hardixacademy/ua_help.git
          cd /home/ec2-user/app/ua_help
          git checkout main
          git pull
          sudo docker-compose stop
          sudo docker-compose rm -f
          sudo docker-compose build
          sudo docker-compose up -d
